# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tires.models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0002_auto_20170912_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('diameter', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_index', models.PositiveIntegerField(blank=True, null=True)),
                ('picture', models.FileField(upload_to=tires.models.directory_path)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tires.Tire')),
            ],
        ),
    ]
