# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import tires.models


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_characteristic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='tire',
        ),
        migrations.AddField(
            model_name='tire',
            name='diameter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=tires.models.directory_path),
        ),
        migrations.AddField(
            model_name='tire',
            name='speed_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
